### ISSUE TITLE
5.0.0 Release Roadmap

### ISSUE THREAD

**Issue by aikoofujimotoo** [aikoofujimotoo/nhentai-cli#11]
This release will include changes and new features. This list is not final and some of the proposed features and changes may be removed.

**Features**

- [ ] Implement Web GUI
  - [ ] Implement support of parallel downloading
  - [ ] Views
      - [ ] Settings
      - [ ] Download View
      - [ ] Gallery View
- [ ] Implement Cover Art display on the CLI when viewing information

**Code**

- [ ] Use SQLite 3 for storing information and metadata instead of JSON.
- [ ] Refactor Image downloading function
- [ ] Use [`superagent`](https://www.npmjs.com/package/superagent) instead of [deprecated request library](https://github.com/request/request/issues/3142)

**Project**

- [ ] Use [`pkg`](https://www.npmjs.com/package/pkg) to pack this project into a single executable.
